[package]
name = "p1emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.0.22", features = ["cargo"] }
anyhow = "1.0.66"
thiserror = "1.0.37"
