M48
; DRILL file {KiCad (7.0.0)} date Sat Dec 30 21:58:13 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-30T21:58:13+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1098
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X1.65Y-1.25
X1.65Y-4.75
T2
X4.475Y-1.22
X4.475Y-4.825
T0
M30
