M48
; DRILL file {KiCad (7.0.0)} date Sat Dec 30 22:17:35 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-30T22:17:35+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1098
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X1.65Y-1.25
X1.65Y-4.75
T2
X4.47Y-4.825
X4.4752Y-1.2204
T0
M30
