M48
; DRILL file {KiCad 8.0.5-8.0.5-0~ubuntu24.04.1} date 2024-09-12T21:54:17+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-12T21:54:17+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-8.0.5-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1098
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X1.65Y-1.25
X1.65Y-4.75
T2
X5.3296Y-4.825
X5.3346Y-1.22
M30
